// src/questions_mother.js
const topics = [
  "1. Unli harflar",
  "2. Undosh harflar",
  "3. Nutq tovushlari",
  "4. Orfografiya",
  "5. Ajratib yozish",
  "6. Chiziqcha bilan yozish",
  "7. X va H harflarini farqlash",
  "8. Shevaga xos so‘zlar",
  "9. Morfologiya",
  "10. Ot so‘z turkumi"
];

const motherTongueQuestions = [
  // 1. Unli harflar (20 ta)
  { question: "O‘zbek tilida nechta unli harf bor?", options: ["A) 8", "B) 6", "C) 10", "D) 11"], correct: 2 },
  { question: "Qalin unlilar qaysilar?", options: ["A) e, i, o‘", "B) a, o‘, u", "C) a, e, i", "D) i, u, o‘"], correct: 1 },
  { question: "“Kitob” so‘zida qanday unli bor?", options: ["A) Yupqa", "B) Qalin", "C) Aralash", "D) Yo‘q"], correct: 1 },
  { question: "Faqat yupqa unlilardan iborat so‘z?", options: ["A) bola", "B) qizil", "C) uy", "D) suv"], correct: 1 },
  { question: "“O‘zbekiston” so‘zida nechta unli bor?", options: ["A) 5", "B) 6", "C) 7", "D) 8"], correct: 1 },
  { question: "“Yigit” so‘zida qanday unli bor?", options: ["A) Faqat yupqa", "B) Faqat qalin", "C) Aralash", "D) Yo‘q"], correct: 0 },
  { question: "“Ko‘z” so‘zida nechta unli bor?", options: ["A) 1", "B) 2", "C) 3", "D) 4"], correct: 1 },
  { question: "“Qor” so‘zida qanday unli?", options: ["A) Qalin", "B) Yupqa", "C) Ikkalasiham", "D) Yo‘q"], correct: 0 },
  { question: "“El” so‘zida qanday unli?", options: ["A) Yupqa", "B) Qalin", "C) Aralash", "D) Yo‘q"], correct: 0 },
  { question: "“Uychi” so‘zida nechta unli?", options: ["A) 2", "B) 3", "C) 4", "D) 5"], correct: 1 },
  { question: "“O‘qituvchi” so‘zida nechta “o‘” bor?", options: ["A) 1", "B) 2", "C) 3", "D) 4"], correct: 1 },
  { question: "“Sevgi” so‘zida nechta unli?", options: ["A) 2", "B) 3", "C) 4", "D) 5"], correct: 1 },
  { question: "“Yurak” so‘zida qanday unli?", options: ["A) Faqat qalin", "B) Faqat yupqa", "C) Aralash", "D) Yo‘q"], correct: 2 },
  { question: "“Kuz” so‘zida nechta unli?", options: ["A) 1", "B) 2", "C) 3", "D) 4"], correct: 1 },
  { question: "“Bahor” so‘zida nechta unli?", options: ["A) 2", "B) 3", "C) 4", "D) 5"], correct: 1 },
  { question: "“Osmonga” so‘zida nechta unli?", options: ["A) 4", "B) 5", "C) 6", "D) 7"], correct: 0 },
  { question: "“Qush” so‘zida nechta unli?", options: ["A) 1", "B) 2", "C) 3", "D) 4"], correct: 1 },
  { question: "“Daraxt” so‘zida nechta unli?", options: ["A) 2", "B) 3", "C) 4", "D) 5"], correct: 1 },
  { question: "“Gullar” so‘zida nechta unli?", options: ["A) 2", "B) 3", "C) 4", "D) 5"], correct: 1 },
  { question: "“Yulduz” so‘zida nechta unli?", options: ["A) 2", "B) 3", "C) 4", "D) 5"], correct: 1 },

  // 2. Undosh harflar (20 ta)
  { question: "O‘zbek alifbosida nechta undosh harf bor?", options: ["A) 22", "B) 24", "C) 26", "D) 28"], correct: 1 },
  { question: "Qaysi harf undosh emas?", options: ["A) b", "B) o", "C) d", "D) g"], correct: 1 },
  { question: "“Sh” qanday harf?", options: ["A) Bitta harf", "B) Ikkita harf", "C) Undosh", "D) Unli"], correct: 2 },
  { question: "“Ng” qaysi so‘zda bor?", options: ["A) kitob", "B) qorong‘i", "C) bola", "D) uy"], correct: 1 },
  { question: "“O‘zbek” so‘zida nechta undosh?", options: ["A) 3", "B) 4", "C) 5", "D) 6"], correct: 2 },
  { question: "O‘zbek tilida yo‘q harf?", options: ["A) w", "B) x", "C) h", "D) q"], correct: 0 },
  { question: "“Maktab” so‘zida nechta undosh?", options: ["A) 4", "B) 5", "C) 6", "D) 7"], correct: 1 },
  { question: "“Telefon” so‘zida nechta undosh?", options: ["A) 5", "B) 6", "C) 7", "D) 8"], correct: 1 },
  { question: "“Kompyuter” so‘zida nechta undosh?", options: ["A) 6", "B) 7", "C) 8", "D) 9"], correct: 2 },
  { question: "“Ch” tovushi qanday?", options: ["A) Jarangli", "B) Jarrangsiz", "C) Ikkalasiham", "D) Yo‘q"], correct: 1 },
  { question: "“G‘” qanday harf?", options: ["A) Undosh", "B) Unli", "C) Yumshoq", "D) Qattiq"], correct: 0 },
  { question: "“Q” tovushi qayerdan chiqadi?", options: ["A) Old", "B) Orqa", "C) O‘rta", "D) Burun"], correct: 1 },
  { question: "“F” harfi asosan qayerdan kelgan?", options: ["A) Arabcha", "B) Ruscha", "C) Inglizcha", "D) O‘zbekcha"], correct: 0 },
  { question: "“V” harfi asosan qayerdan kelgan?", options: ["A) Ruscha", "B) Arabcha", "C) O‘zbekcha", "D) Turkcha"], correct: 0 },
  { question: "“Yo‘q” so‘zida nechta undosh?", options: ["A) 2", "B) 3", "C) 4", "D) 5"], correct: 0 },
  { question: "“Ha” so‘zida nechta undosh?", options: ["A) 1", "B) 2", "C) 3", "D) 4"], correct: 0 },
  { question: "“Xayr” so‘zida nechta undosh?", options: ["A) 3", "B) 4", "C) 5", "D) 6"], correct: 0 },
  { question: "“Salom” so‘zida nechta undosh?", options: ["A) 3", "B) 4", "C) 5", "D) 6"], correct: 1 },
  { question: "“Rahmat” so‘zida nechta undosh?", options: ["A) 4", "B) 5", "C) 6", "D) 7"], correct: 1 },
  { question: "“Marhamat” so‘zida nechta undosh?", options: ["A) 6", "B) 7", "C) 8", "D) 9"], correct: 1 },

  // 3. Nutq tovushlari (20 ta)
  { question: "Nutq tovushlari nechaga bo‘linadi?", options: ["A) 1", "B) 2", "C) 3", "D) 4"], correct: 1 },
  { question: "Unli tovushlar nechta?", options: ["A) 6", "B) 8", "C) 9", "D) 10"], correct: 2 },
  { question: "Undosh tovushlar nechta?", options: ["A) 24", "B) 26", "C) 28", "D) 30"], correct: 0 },
  { question: "Jarangli undoshlar misoli?", options: ["A) p, t, k", "B) b, d, g", "C) s, sh", "D) f, x"], correct: 1 },
  { question: "Jarrangsiz undoshlar misoli?", options: ["A) b, d, g", "B) p, t, k", "C) m, n", "D) l, r"], correct: 1 },
  { question: "“O‘zbek” so‘zida nechta tovush?", options: ["A) 5", "B) 6", "C) 7", "D) 8"], correct: 1 },
  { question: "“Kitob” so‘zida nechta tovush?", options: ["A) 4", "B) 5", "C) 6", "D) 7"], correct: 1 },
  { question: "“Maktab” so‘zida nechta tovush?", options: ["A) 5", "B) 6", "C) 7", "D) 8"], correct: 1 },
  { question: "“O‘qituvchi” so‘zida nechta tovush?", options: ["A) 8", "B) 9", "C) 10", "D) 11"], correct: 2 },
  { question: "“Bolalar” so‘zida nechta tovush?", options: ["A) 6", "B) 7", "C) 8", "D) 9"], correct: 1 },
  { question: "Tovush va harf bir xilmi?", options: ["A) Ha", "B) Yo‘q", "C) Ba’zida", "D) Hech qachon"], correct: 1 },
  { question: "“Yaxshi” so‘zida nechta tovush?", options: ["A) 5", "B) 6", "C) 7", "D) 8"], correct: 0 },
  { question: "“Qanday” so‘zida nechta tovush?", options: ["A) 6", "B) 7", "C) 8", "D) 9"], correct: 0 },
  { question: "“Rahmat” so‘zida nechta tovush?", options: ["A) 6", "B) 7", "C) 8", "D) 9"], correct: 0 },
  { question: "“Salomat” so‘zida nechta tovush?", options: ["A) 7", "B) 8", "C) 9", "D) 10"], correct: 0 },
  { question: "“Xayr” so‘zida nechta tovush?", options: ["A) 3", "B) 4", "C) 5", "D) 6"], correct: 0 },
  { question: "“Assalom” so‘zida nechta tovush?", options: ["A) 7", "B) 8", "C) 9", "D) 10"], correct: 0 },
  { question: "“O‘zbekcha” so‘zida nechta tovush?", options: ["A) 8", "B) 9", "C) 10", "D) 11"], correct: 1 },
  { question: "“Inson” so‘zida nechta tovush?", options: ["A) 5", "B) 6", "C) 7", "D) 8"], correct: 0 },
  { question: "“Do‘st” so‘zida nechta tovush?", options: ["A) 4", "B) 5", "C) 6", "D) 7"], correct: 0 },

  // 4. Orfografiya (20 ta)
  { question: "“Kitob” so‘zi to‘g‘ri yozilganmi?", options: ["A) Ha", "B) Yo‘q", "C) Kitab", "D) Kitop"], correct: 0 },
  { question: "“O‘zbek” so‘zida qanday belgi bor?", options: ["A) ‘", "B) -", "C) ’", "D) yo‘q"], correct: 0 },
  { question: "“Telefon” so‘zida qanday harf ishlatiladi?", options: ["A) f", "B) p", "C) v", "D) t"], correct: 0 },
  { question: "“Kompyuter” so‘zi to‘g‘ri yozilganmi?", options: ["A) Ha", "B) Yo‘q", "C) Komputer", "D) Kampyuter"], correct: 0 },
  { question: "“Internet” so‘zi qanday boshlanadi?", options: ["A) I", "B) i", "C) İn", "D) in"], correct: 0 },
  { question: "“O‘zbekiston” so‘zida nechta “o‘” bor?", options: ["A) 1", "B) 2", "C) 3", "D) 4"], correct: 1 },
  { question: "“Respublika” so‘zi qanday boshlanadi?", options: ["A) R", "B) r", "C) Re", "D) re"], correct: 0 },
  { question: "“Davlat” so‘zi qanday yoziladi?", options: ["A) davlat", "B) dawlat", "C) davlat'", "D) davlat’"], correct: 0 },
  { question: "“Xalq” so‘zi qanday yoziladi?", options: ["A) xalq", "B) halq", "C) xalq'", "D) xalq’"], correct: 0 },
  { question: "“Milliy” so‘zi to‘g‘ri yozilganmi?", options: ["A) Ha", "B) Yo‘q", "C) Miliy", "D) Milliyy"], correct: 0 },
  { question: "“San’at” so‘zida qanday belgi bor?", options: ["A) ‘", "B) -", "C) ’", "D) yo‘q"], correct: 0 },
  { question: "“Adabiyot” so‘zida nechta “a” bor?", options: ["A) 3", "B) 4", "C) 5", "D) 6"], correct: 0 },
  { question: "“Tarix” so‘zi qanday yoziladi?", options: ["A) tarix", "B) tarih", "C) tarix'", "D) tarix’"], correct: 0 },
  { question: "“Matematika” so‘zida nechta “a” bor?", options: ["A) 4", "B) 5", "C) 6", "D) 7"], correct: 0 },
  { question: "“Fizika” so‘zi qanday yoziladi?", options: ["A) fizika", "B) phizika", "C) fizyka", "D) fizica"], correct: 0 },
  { question: "“Kimyo” so‘zi to‘g‘ri yozilganmi?", options: ["A) Ha", "B) Yo‘q", "C) Kimeyo", "D) Kimya"], correct: 0 },
  { question: "“Biologiya” so‘zida nechta “o” bor?", options: ["A) 2", "B) 3", "C) 4", "D) 5"], correct: 0 },
  { question: "“Informatika” so‘zida nechta “i” bor?", options: ["A) 3", "B) 4", "C) 5", "D) 6"], correct: 0 },
  { question: "“Sport” so‘zi qanday yoziladi?", options: ["A) sport", "B) sport'", "C) sport’", "D) spart"], correct: 0 },
  { question: "“Musiqa” so‘zida nechta “i” bor?", options: ["A) 1", "B) 2", "C) 3", "D) 4"], correct: 1 },

  // 5. Ajratib yozish (20 ta)
  { question: "“Bir joyda” qanday yoziladi?", options: ["A) birjoyda", "B) bir joyda", "C) bir-joyda", "D) birjoy’da"], correct: 1 },
  { question: "“Hech qachon” qanday yoziladi?", options: ["A) hechqachon", "B) hech qachon", "C) hech-qachon", "D) hechqachon’"], correct: 1 },
  { question: "“Hamma narsa” qanday yoziladi?", options: ["A) hammnarsa", "B) hamma narsa", "C) hamma-narsa", "D) hammanarsa"], correct: 1 },
  { question: "“Albatta” qanday yoziladi?", options: ["A) albatta", "B) albat ta", "C) al-batta", "D) albattta"], correct: 0 },
  { question: "“Har doim” qanday yoziladi?", options: ["A) hardoim", "B) har doim", "C) har-doim", "D) har doym"], correct: 1 },
  { question: "“Bir kun” qanday yoziladi?", options: ["A) birkun", "B) bir kun", "C) bir-kun", "D) birku’n"], correct: 1 },
  { question: "“Ko‘p narsa” qanday yoziladi?", options: ["A) ko‘pnarsa", "B) ko‘p narsa", "C) ko‘p-narsa", "D) ko‘pnar’sa"], correct: 1 },
  { question: "“Yana bir” qanday yoziladi?", options: ["A) yanabir", "B) yana bir", "C) yana-bir", "D) yanabir’"], correct: 1 },
  { question: "“Hali ham” qanday yoziladi?", options: ["A) haliham", "B) hali ham", "C) hali-ham", "D) halilham"], correct: 1 },
  { question: "“Endi ham” qanday yoziladi?", options: ["A) endiham", "B) endi ham", "C) endi-ham", "D) endiham’"], correct: 1 },
  { question: "“Shu bilan” qanday yoziladi?", options: ["A) shubilan", "B) shu bilan", "C) shu-bilan", "D) shubilan’"], correct: 1 },
  { question: "“Bir oz” qanday yoziladi?", options: ["A) biroz", "B) bir oz", "C) bir-oz", "D) bi’roz"], correct: 1 },
  { question: "“Juda ko‘p” qanday yoziladi?", options: ["A) judako‘p", "B) juda ko‘p", "C) juda-ko‘p", "D) judakop"], correct: 1 },
  { question: "“Anchayin” qanday yoziladi?", options: ["A) anchayin", "B) ancha yin", "C) ancha-yin", "D) anchayin’"], correct: 0 },
  { question: "“Yomon emas” qanday yoziladi?", options: ["A) yomonemas", "B) yomon emas", "C) yomon-emas", "D) yomonemas’"], correct: 1 },
  { question: "“Juda yaxshi” qanday yoziladi?", options: ["A) judayaxshi", "B) juda yaxshi", "C) juda-yaxshi", "D) judayaxshiy"], correct: 1 },
  { question: "“Hamma joyda” qanday yoziladi?", options: ["A) hammajoyda", "B) hamma joyda", "C) hamma-joyda", "D) hammajoy’da"], correct: 1 },
  { question: "“Hech kim” qanday yoziladi?", options: ["A) hechkim", "B) hech kim", "C) hech-kim", "D) hechkim’"], correct: 1 },
  { question: "“Bir necha” qanday yoziladi?", options: ["A) birnecha", "B) bir necha", "C) bir-necha", "D) birnech’a"], correct: 1 },
  { question: "“Shunday qilib” qanday yoziladi?", options: ["A) shundayqilib", "B) shunday qilib", "C) shunday-qilib", "D) shundayqili’b"], correct: 1 },

  // 6. Chiziqcha bilan yozish (20 ta)
  { question: "“Ota-ona” qanday yoziladi?", options: ["A) otaona", "B) ota ona", "C) ota-ona", "D) ota’ona"], correct: 2 },
  { question: "“Qizil-qo‘lda” qanday yoziladi?", options: ["A) qizilqo‘lda", "B) qizil qo‘lda", "C) qizil-qo‘lda", "D) qizilqo‘ldo"], correct: 2 },
  { question: "“Yashil-yashil” qanday yoziladi?", options: ["A) yashilyashil", "B) yashil yashil", "C) yashil-yashil", "D) yashil’yashil"], correct: 2 },
  { question: "“Katta-katta” qanday yoziladi?", options: ["A) kattakatta", "B) katta katta", "C) katta-katta", "D) katta’katta"], correct: 2 },
  { question: "“O‘zbek-turk” qanday yoziladi?", options: ["A) o‘zbekturk", "B) o‘zbek turk", "C) o‘zbek-turk", "D) o‘zbek’turk"], correct: 2 },
  { question: "“Er-xotin” qanday yoziladi?", options: ["A) erxotin", "B) er xotin", "C) er-xotin", "D) er’xotin"], correct: 2 },
  { question: "“Ona-bola” qanday yoziladi?", options: ["A) onabola", "B) ona bola", "C) ona-bola", "D) ona’bola"], correct: 2 },
  { question: "“Yigit-qiz” qanday yoziladi?", options: ["A) yigitqiz", "B) yigit qiz", "C) yigit-qiz", "D) yigit’qiz"], correct: 2 },
  { question: "“Ko‘k-yashil” qanday yoziladi?", options: ["A) ko‘kyashil", "B) ko‘k yashil", "C) ko‘k-yashil", "D) ko‘k’yashil"], correct: 2 },
  { question: "“Qora-qosh” qanday yoziladi?", options: ["A) qoraqosh", "B) qora qosh", "C) qora-qosh", "D) qora’qosh"], correct: 2 },
  { question: "“Sariq-soch” qanday yoziladi?", options: ["A) sariqsoch", "B) sariq soch", "C) sariq-soch", "D) sariq’soch"], correct: 2 },
  { question: "“Qizil-qalpoq” qanday yoziladi?", options: ["A) qizilqalpoq", "B) qizil qalpoq", "C) qizil-qalpoq", "D) qizil’qalpoq"], correct: 2 },
  { question: "“Oltin-soch” qanday yoziladi?", options: ["A) oltinsoch", "B) oltin soch", "C) oltin-soch", "D) oltin’soch"], correct: 2 },
  { question: "“Yangi-yangi” qanday yoziladi?", options: ["A) yangiyangi", "B) yangi yangi", "C) yangi-yangi", "D) yangi’yangi"], correct: 2 },
  { question: "“Tosh-tosh” qanday yoziladi?", options: ["A) toshtosh", "B) tosh tosh", "C) tosh-tosh", "D) tosh’tosh"], correct: 2 },
  { question: "“Qor-qor” qanday yoziladi?", options: ["A) qorqor", "B) qor qor", "C) qor-qor", "D) qor’qor"], correct: 2 },
  { question: "“Issiq-issiq” qanday yoziladi?", options: ["A) issiqissiq", "B) issiq issiq", "C) issiq-issiq", "D) issiq’issiq"], correct: 2 },
  { question: "“Sovuq-sovuq” qanday yoziladi?", options: ["A) sovuqsovuq", "B) sovuq sovuq", "C) sovuq-sovuq", "D) sovuq’sovuq"], correct: 2 },
  { question: "“Yor-yor” qanday yoziladi?", options: ["A) yoryor", "B) yor yor", "C) yor-yor", "D) yor’yor"], correct: 2 },
  { question: "“Do‘st-do‘st” qanday yoziladi?", options: ["A) do‘stdo‘st", "B) do‘st do‘st", "C) do‘st-do‘st", "D) do‘st’do‘st"], correct: 2 },

  // 7. X va H harflarini farqlash (20 ta)
  { question: "“Xayr” so‘zi qanday yoziladi?", options: ["A) hayr", "B) xayr", "C) xair", "D) hayir"], correct: 1 },
  { question: "“Hamma” so‘zi qanday yoziladi?", options: ["A) xamma", "B) hamma", "C) hamme", "D) xamme"], correct: 1 },
  { question: "“Xato” so‘zi qanday yoziladi?", options: ["A) hato", "B) xato", "C) xata", "D) hata"], correct: 1 },
  { question: "“Havo” so‘zi qanday yoziladi?", options: ["A) xavo", "B) havo", "C) hava", "D) xava"], correct: 1 },
  { question: "“Xabar” so‘zi qanday yoziladi?", options: ["A) habar", "B) xabar", "C) xabor", "D) habar"], correct: 1 },
  { question: "“Harakat” so‘zi qanday yoziladi?", options: ["A) xarakat", "B) harakat", "C) harekat", "D) xarekat"], correct: 1 },
  { question: "“Xohish” so‘zi qanday yoziladi?", options: ["A) hohish", "B) xohish", "C) xoxish", "D) hoxish"], correct: 1 },
  { question: "“Hikoya” so‘zi qanday yoziladi?", options: ["A) xikoya", "B) hikoya", "C) hikaya", "D) xikaya"], correct: 1 },
  { question: "“Xursand” so‘zi qanday yoziladi?", options: ["A) hursand", "B) xursand", "C) xursant", "D) hursant"], correct: 1 },
  { question: "“Holat” so‘zi qanday yoziladi?", options: ["A) xolat", "B) holat", "C) halat", "D) xalat"], correct: 1 },
  { question: "“Xavf” so‘zi qanday yoziladi?", options: ["A) havf", "B) xavf", "C) xawf", "D) hawf"], correct: 1 },
  { question: "“Hukm” so‘zi qanday yoziladi?", options: ["A) xukm", "B) hukm", "C) hukum", "D) xukum"], correct: 1 },
  { question: "“Xotira” so‘zi qanday yoziladi?", options: ["A) hotira", "B) xotira", "C) xotiro", "D) hotiro"], correct: 1 },
  { question: "“Hunar” so‘zi qanday yoziladi?", options: ["A) xunar", "B) hunar", "C) hunor", "D) xunor"], correct: 1 },
  { question: "“Xizmat” so‘zi qanday yoziladi?", options: ["A) hizmat", "B) xizmat", "C) xizmat", "D) hizmat"], correct: 1 },
  { question: "“Hafta” so‘zi qanday yoziladi?", options: ["A) xafta", "B) hafta", "C) haffa", "D) xaffa"], correct: 1 },
  { question: "“Xalq” so‘zi qanday yoziladi?", options: ["A) halq", "B) xalq", "C) xalk", "D) halk"], correct: 1 },
  { question: "“Harakat” so‘zi qanday yoziladi?", options: ["A) xarakat", "B) harakat", "C) hareket", "D) xareket"], correct: 1 },
  { question: "“Xona” so‘zi qanday yoziladi?", options: ["A) hona", "B) xona", "C) xone", "D) hone"], correct: 1 },
  { question: "“Hamma” so‘zi qanday yoziladi?", options: ["A) xamma", "B) hamma", "C) hamme", "D) xamme"], correct: 1 },

  // 8. Shevaga xos so‘zlar (20 ta)
  { question: "Toshkent shevasida “nima” o‘rniga nima deyiladi?", options: ["A) nima", "B) ne", "C) nema", "D) nimadur"], correct: 1 },
  { question: "Farg‘onada “yaxshi” o‘rniga nima deyiladi?", options: ["A) yaxshi", "B) zor", "C) ajoyib", "D) yomon"], correct: 1 },
  { question: "Surxondaryoda “bola” o‘rniga nima deyiladi?", options: ["A) bola", "B) bala", "C) bolla", "D) balo"], correct: 1 },
  { question: "Qashqadaryoda “kel” o‘rniga nima deyiladi?", options: ["A) kel", "B) ke", "C) keli", "D) kelib"], correct: 1 },
  { question: "Andijonda “bor” o‘rniga nima deyiladi?", options: ["A) bor", "B) bo‘", "C) boru", "D) bar"], correct: 1 },
  { question: "Samarqandda “yur” o‘rniga nima deyiladi?", options: ["A) yur", "B) yugur", "C) yugir", "D) yurib"], correct: 2 },
  { question: "Buxoroda “qanaqa” o‘rniga nima deyiladi?", options: ["A) qanaqa", "B) qanday", "C) qalay", "D) qaysi"], correct: 2 },
  { question: "Xorazmda “nima qilyapsan” o‘rniga nima deyiladi?", options: ["A) nima qilyapsan", "B) neme qilyapsan", "C) ne qilyapsan", "D) nimadur qilyapsan"], correct: 2 },
  { question: "Qoraqalpog‘istonda “yaxshi” o‘rniga nima deyiladi?", options: ["A) yaxshi", "B) jaqsi", "C) zor", "D) ajoyib"], correct: 1 },
  { question: "Namanganda “bor” o‘rniga nima deyiladi?", options: ["A) bor", "B) bar", "C) bo‘", "D) boru"], correct: 1 },
  { question: "Jizzaxda “kel” o‘rniga nima deyiladi?", options: ["A) kel", "B) ke", "C) keli", "D) kelib"], correct: 1 },
  { question: "Sirdaryoda “yaxshi” o‘rniga nima deyiladi?", options: ["A) yaxshi", "B) zor", "C) yaxshiyam", "D) ajoyib"], correct: 1 },
  { question: "Navoiyda “nima” o‘rniga nima deyiladi?", options: ["A) nima", "B) ne", "C) nema", "D) nimadur"], correct: 1 },
  { question: "Toshkent viloyatida “bor” o‘rniga nima deyiladi?", options: ["A) bor", "B) bo‘", "C) bar", "D) boru"], correct: 1 },
  { question: "Andijonda “qanaqa” o‘rniga nima deyiladi?", options: ["A) qanaqa", "B) qanday", "C) qalay", "D) qaysi"], correct: 2 },
  { question: "Farg‘onada “yur” o‘rniga nima deyiladi?", options: ["A) yur", "B) yugir", "C) yugur", "D) yurib"], correct: 1 },
  { question: "Surxondaryoda “kel” o‘rniga nima deyiladi?", options: ["A) kel", "B) ke", "C) keli", "D) kelib"], correct: 1 },
  { question: "Qashqadaryoda “nima” o‘rniga nima deyiladi?", options: ["A) nima", "B) ne", "C) nema", "D) nimadur"], correct: 1 },
  { question: "Buxoroda “yaxshi” o‘rniga nima deyiladi?", options: ["A) yaxshi", "B) zor", "C) jaqsi", "D) ajoyib"], correct: 1 },
  { question: "Xorazmda “bor” o‘rniga nima deyiladi?", options: ["A) bor", "B) bar", "C) bo‘", "D) boru"], correct: 1 },

  // 9. Morfologiya (20 ta)
  { question: "So‘z qismlari nechta?", options: ["A) 8", "B) 9", "C) 10", "D) 11"], correct: 2 },
  { question: "“Kitob” so‘zi qaysi so‘z turkumiga kiradi?", options: ["A) Ot", "B) Sifat", "C) Fe’l", "D) Ravish"], correct: 0 },
  { question: "“Yaxshi” so‘zi qaysi so‘z turkumiga kiradi?", options: ["A) Ot", "B) Sifat", "C) Fe’l", "D) Ravish"], correct: 1 },
  { question: "“Yugurdi” so‘zi qaysi so‘z turkumiga kiradi?", options: ["A) Ot", "B) Sifat", "C) Fe’l", "D) Ravish"], correct: 2 },
  { question: "“Tez” so‘zi qaysi so‘z turkumiga kiradi?", options: ["A) Ot", "B) Sifat", "C) Fe’l", "D) Ravish"], correct: 3 },
  { question: "“U” so‘zi qaysi so‘z turkumiga kiradi?", options: ["A) Olmosh", "B) Ot", "C) Sifat", "D) Son"], correct: 0 },
  { question: "“Besh” so‘zi qaysi so‘z turkumiga kiradi?", options: ["A) Son", "B) Ot", "C) Sifat", "D) Ravish"], correct: 0 },
  { question: "“Va” so‘zi qaysi so‘z turkumiga kiradi?", options: ["A) Bog‘lovchi", "B) Yordamchi", "C) Undov", "D) Ravish"], correct: 0 },
  { question: "“Ey” so‘zi qaysi so‘z turkumiga kiradi?", options: ["A) Undov", "B) Bog‘lovchi", "C) Yordamchi", "D) Ot"], correct: 0 },
  { question: "“Bilmayman” so‘zida nechta so‘z?", options: ["A) 1", "B) 2", "C) 3", "D) 4"], correct: 0 },
  { question: "“Kitoblarim” so‘zida nechta qo‘shimcha bor?", options: ["A) 1", "B) 2", "C) 3", "D) 4"], correct: 1 },
  { question: "“O‘qiganman” so‘zida nechta qo‘shimcha bor?", options: ["A) 1", "B) 2", "C) 3", "D) 4"], correct: 2 },
  { question: "“Kelishingiz” so‘zida nechta qo‘shimcha bor?", options: ["A) 2", "B) 3", "C) 4", "D) 5"], correct: 2 },
  { question: "“Yozganlar” so‘zida nechta qo‘shimcha bor?", options: ["A) 1", "B) 2", "C) 3", "D) 4"], correct: 1 },
  { question: "“Boribdi” so‘zida nechta qo‘shimcha bor?", options: ["A) 1", "B) 2", "C) 3", "D) 4"], correct: 1 },
  { question: "“Kelmayapman” so‘zida nechta qo‘shimcha bor?", options: ["A) 2", "B) 3", "C) 4", "D) 5"], correct: 2 },
  { question: "“Yuribsiz” so‘zida nechta qo‘shimcha bor?", options: ["A) 1", "B) 2", "C) 3", "D) 4"], correct: 1 },
  { question: "“O‘qiyotgan” so‘zida nechta qo‘shimcha bor?", options: ["A) 1", "B) 2", "C) 3", "D) 4"], correct: 1 },
  { question: "“Kelganman” so‘zida nechta qo‘shimcha bor?", options: ["A) 1", "B) 2", "C) 3", "D) 4"], correct: 1 },
  { question: "“Yozilgan” so‘zida nechta qo‘shimcha bor?", options: ["A) 1", "B) 2", "C) 3", "D) 4"], correct: 0 },

  // 10. Ot so‘z turkumi (20 ta)
  { question: "Otning asosiy vazifasi nima?", options: ["A) Harakat bildirish", "B) Narsa bildirish", "C) Belgini bildirish", "D) Miqdor bildirish"], correct: 1 },
  { question: "“Kitob” otning qaysi turi?", options: ["A) Umumiy", "B) Maxsus", "C) Yashirin", "D) Abstrakt"], correct: 0 },
  { question: "“O‘zbekiston” otning qaysi turi?", options: ["A) Umumiy", "B) Maxsus", "C) Yashirin", "D) Abstrakt"], correct: 1 },
  { question: "“Sevgi” otning qaysi turi?", options: ["A) Umumiy", "B) Maxsus", "C) Yashirin", "D) Abstrakt"], correct: 3 },
  { question: "“O‘qituvchi” otning qaysi turi?", options: ["A) Umumiy", "B) Maxsus", "C) Kasb", "D) Abstrakt"], correct: 2 },
  { question: "“Daraxt” otning qaysi turi?", options: ["A) Umumiy", "B) Maxsus", "C) Yashirin", "D) Hayvon"], correct: 0 },
  { question: "“Odam” otning qaysi turi?", options: ["A) Umumiy", "B) Maxsus", "C) Yashirin", "D) Abstrakt"], correct: 0 },
  { question: "“Toshkent” otning qaysi turi?", options: ["A) Umumiy", "B) Maxsus", "C) Yashirin", "D) Abstrakt"], correct: 1 },
  { question: "“Do‘stlik” otning qaysi turi?", options: ["A) Umumiy", "B) Maxsus", "C) Yashirin", "D) Abstrakt"], correct: 3 },
  { question: "“Maktab” otning qaysi turi?", options: ["A) Umumiy", "B) Maxsus", "C) Yashirin", "D) Abstrakt"], correct: 0 },
  { question: "“Inson” otning qaysi turi?", options: ["A) Umumiy", "B) Maxsus", "C) Yashirin", "D) Abstrakt"], correct: 0 },
  { question: "“O‘zbek” otning qaysi turi?", options: ["A) Umumiy", "B) Maxsus", "C) Millat", "D) Abstrakt"], correct: 2 },
  { question: "“Suv” otning qaysi turi?", options: ["A) Umumiy", "B) Maxsus", "C) Yashirin", "D) Modda"], correct: 3 },
  { question: "“Havo” otning qaysi turi?", options: ["A) Umumiy", "B) Maxsus", "C) Yashirin", "D) Modda"], correct: 3 },
  { question: "“Yigit” otning qaysi turi?", options: ["A) Umumiy", "B) Maxsus", "C) Yashirin", "D) Abstrakt"], correct: 0 },
  { question: "“Qiz” otning qaysi turi?", options: ["A) Umumiy", "B) Maxsus", "C) Yashirin", "D) Abstrakt"], correct: 0 },
  { question: "“Bola” otning qaysi turi?", options: ["A) Umumiy", "B) Maxsus", "C) Yashirin", "D) Abstrakt"], correct: 0 },
  { question: "“Ona” otning qaysi turi?", options: ["A) Umumiy", "B) Maxsus", "C) Qarindoshlik", "D) Abstrakt"], correct: 2 },
  { question: "“Ota” otning qaysi turi?", options: ["A) Umumiy", "B) Maxsus", "C) Qarindoshlik", "D) Abstrakt"], correct: 2 },
  { question: "“Uka” otning qaysi turi?", options: ["A) Umumiy", "B) Maxsus", "C) Qarindoshlik", "D) Abstrakt"], correct: 2 }
];

module.exports = { topics, motherTongueQuestions };